- name: Configure Database Server
  hosts: dbservers
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Install MariaDB
      command: yum install -y mariadb-server

    - name: Backup original MySQL config
      command: cp /etc/my.cnf /etc/my.cnf.bak

    - name: Allow remote connections in MariaDB
      shell: echo "bind-address = 0.0.0.0" >> /etc/my.cnf

    - name: Start and enable MySQL
      service:
        name: mariadb
        state: started
        enabled: yes


    - name: Configure MariaDB - Create Database and User
      shell: |
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
        sudo mysql -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ db_user }}'@'%';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Copy SQL script for product inventory
      copy:
        dest: "/tmp/db-load-script.sql"
        content: |
          USE {{ db_name }};
          CREATE TABLE IF NOT EXISTS products (
            id mediumint(8) unsigned NOT NULL auto_increment,
            Name varchar(255) default NULL,
            Price varchar(255) default NULL,
            ImageUrl varchar(255) default NULL,
            PRIMARY KEY (id)
          ) AUTO_INCREMENT=1;

          INSERT INTO products (Name,Price,ImageUrl) VALUES
            ("Laptop","100","c-1.png"),
            ("Drone","200","c-2.png"),
            ("VR","300","c-3.png"),
            ("Tablet","50","c-5.png"),
            ("Watch","90","c-6.png"),
            ("Phone Covers","20","c-7.png"),
            ("Phone","80","c-8.png"),
            ("Laptop","150","c-4.png");

    - name: Load product inventory data
      shell: sudo mysql < /tmp/db-load-script.sql

- name: Configure Web Server
  hosts: webservers
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Install Apache (HTTPD)
      command: yum install -y httpd

    - name: Install PHP
      command: yum install -y php

    - name: Install MariaDB
      command: yum install -y mariadb-server

    - name: Install PHP MySQL Extension
      command: yum install -y php-mysqlnd

    - name: Install Git
      command: yum install -y git
    
    - name: Change DirectoryIndex to use index.php by default
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DirectoryIndex'
        line: 'DirectoryIndex index.php'

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MySQL
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Clone the e-commerce application
      git:
        repo: "https://github.com/MohamedAwad9k8/ecommerce-project"
        dest: "/var/www/html"

    - name: Create .env file with database connection details
      copy:
        dest: "/var/www/html/.env"
        content: |
          DB_HOST={{ db_host }}
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
          DB_NAME={{ db_name }}
  
    - name: Restart Apache after deployment
      service:
        name: httpd
        state: restarted
